out_path=data/raw_data/oas
mkdir -p $out_path

wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279050_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279051_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279054_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279055_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279058_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279059_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279062_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279063_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279066_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279067_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279070_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279071_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279074_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279075_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279078_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1279079_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1287196_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1287197_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1287204_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Jaffe_2022/csv/1287205_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/King_2020_2/csv/ERR4082227_paired.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/King_2020_2/csv/ERR4082235_paired.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/King_2020_2/csv/ERR4082243_paired.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/King_2020_2/csv/ERR4082251_paired.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/King_2020_2/csv/ERR4082259_paired.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/King_2020_2/csv/ERR4082263_paired.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/1a_S1__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/1b_S2__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/1c_S3__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/1d_S4__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/1e_S5__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/1f_S6__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/2a_S6__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/2b_S7__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/2c_S8__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/3a_S3__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/3a_S4__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/3b_S4__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/3b_S5__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/3c_S5__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/3c_S6__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/3d_S6__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/3d_S7__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/3e_S7__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/3e_S8__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/AT6md_S1__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/AT6me_S2__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/AT7ma_S7__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/AT7mb_S1__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/AT7mc_S2__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/AT7md_S3__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Phad_2022/csv_paired/AT7me_S4__1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Ramesh_2020/csv/SRR12483491_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Ramesh_2020/csv/SRR12483492_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Ramesh_2020/csv/SRR12483514_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Ramesh_2020/csv/SRR12483516_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Ramesh_2020/csv/SRR12483518_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Ramesh_2020/csv/SRR12483481_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Ramesh_2020/csv/SRR12483486_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Sokal_2021/csv/SCoV10_M0_Sort1_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Sokal_2021/csv/SCoV10_M0_Sort2_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Sokal_2021/csv/SCoV10_M6_Sort1_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Sokal_2021/csv/SCoV11_M0_Sort1_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Sokal_2021/csv/SCoV11_M0_Sort2_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Sokal_2021/csv/SCoV11_M6_Sort1_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Sokal_2021/csv/SCoV13_M0_Sort1_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Sokal_2021/csv/SCoV13_M0_Sort2_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Sokal_2021/csv/SCoV13_M6_Sort1_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Sokal_2021/csv/SCoV1_M0_Sort1_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Sokal_2021/csv/SCoV1_M0_Sort2_1_Paired_All.csv.gz -P $out_path
wget https://opig.stats.ox.ac.uk/webapps/ngsdb/paired/Sokal_2021/csv/SCoV1_M6_Sort1_1_Paired_All.csv.gz -P $out_path